import { Institute } from './types';

export const INITIAL_INSTITUTES: Institute[] = [
  { id: 1, name: "PGIMER", city: "Chandigarh", course: "DM Clinical Immunology", seats: "Unknown" },
  { id: 2, name: "SGPGI", city: "Lucknow", course: "DM Clinical Immunology & Rheumatology", seats: "Unknown" },
  { id: 3, name: "KGMU", city: "Lucknow", course: "DM Clinical Immunology & Rheumatology", seats: "Unknown" },
  { id: 4, name: "CMC", city: "Vellore", course: "DM Clinical Immunology & Rheumatology", seats: 6 },
  { id: 5, name: "JIPMER", city: "Puducherry", course: "DM Rheumatology", seats: "Unknown" },
  { id: 6, name: "Institute of Liver and Biliary Sciences (ILBS)", city: "New Delhi", course: "DNB Rheumatology", seats: "Unknown" },
  { id: 7, name: "Sir Gangaram Hospital", city: "New Delhi", course: "DNB Clinical Immunology & Rheumatology", seats: 2 },
  { id: 8, name: "Amrita Institute of Medical Sciences (AIMS)", city: "Kochi", course: "DM Clinical Immunology & Rheumatology", seats: 2 },
  { id: 9, name: "CARE Hospital", city: "Kochi", course: "DNB Rheumatology", seats: "Unknown" },
  { id: 10, name: "Madras Medical College", city: "Chennai", course: "DM Clinical Immunology & Rheumatology", seats: 4 },
  { id: 11, name: "Nizam's Institute of Medical Sciences (NIMS)", city: "Hyderabad", course: "DM Clinical Immunology & Rheumatology", seats: 4 },
  { id: 12, name: "IPGMER and SSKM Hospital", city: "Kolkata", course: "DM Clinical Immunology & Rheumatology", seats: 2 },
  { id: 13, name: "AIIMS", city: "Rishikesh", course: "DM Clinical Immunology & Rheumatology", seats: 2 },
  { id: 14, name: "Fortis Memorial Research Institute", city: "Gurugram", course: "DNB Rheumatology", seats: "Nil" },
  { id: 15, name: "Medanta", city: "Gurugram", course: "DNB/DM Rheumatology", seats: 2 },
  { id: 16, name: "SRMC/SRIHER Medical College", city: "Chennai", course: "DM Rheumatology", seats: 3 },
  { id: 17, name: "Kalinga Institute of Medical Sciences (KIMS)", city: "Bhubaneswar", course: "DM Clinical Immunology & Rheumatology", seats: 2 },
  { id: 18, name: "Bharati Vidyapeeth University Medical College", city: "Pune", course: "DNB Clinical Immunology & Rheumatology", seats: 2 },
  { id: 19, name: "Hinduja Hospital", city: "Mumbai", course: "DNB Rheumatology", seats: 1 },
  { id: 20, name: "AHRR (Army Hospital R&R)", city: "New Delhi", course: "DNB Rheumatology", seats: 1 },
  { id: 21, name: "IMS SUM Hospital", city: "Bhubaneswar", course: "DNB Rheumatology", seats: 2 },
  { id: 22, name: "SCB Medical College", city: "Cuttack", course: "DM Rheumatology", seats: 2 },
  { id: 23, name: "TNMC (Nair Hospital)", city: "Mumbai", course: "DM Rheumatology", seats: 2 },
  { id: 24, name: "KIMS (Krishna Institute)", city: "Secunderabad", course: "DNB Rheumatology", seats: 2 },
  { id: 25, name: "ESIC Medical College", city: "Hyderabad", course: "DNB Rheumatology", seats: 1 },
  { id: 26, name: "AIG Hospitals", city: "Hyderabad", course: "DNB Rheumatology", seats: 1 },
  { id: 27, name: "Yashoda Hospitals", city: "Hyderabad", course: "DNB Rheumatology", seats: 1 },
  { id: 28, name: "SMS Medical College", city: "Jaipur", course: "DM Rheumatology", seats: 2 },
  { id: 29, name: "Kerala Institute of Medical Sciences", city: "Trivandrum", course: "DrNB Rheumatology", seats: 1 },
  { id: 30, name: "AIIMS", city: "Bilaspur", course: "DM Clinical Immunology & Rheumatology", seats: 2 },
  { id: 31, name: "AIIMS", city: "Kalyani", course: "DM Rheumatology", seats: 1 }
];